### ISSUE TITLE
Asynchronous Interceptors

### ISSUE THREAD

**Issue by eddiekaiger** [connectrpc/connect-swift#104]
Brought this up to @rebello95. It looks like interceptors are currently synchronous, but it would be great if they could be `async` if possible. A common use case is using an interceptor to potentially re-authenticate an expired token before continuing on with the request.

**Comment by rebello95** [comment]
Thanks for flagging this @eddiekaiger! I'll see if I can prioritize this - it'll require a bit of rewiring within the library, but I think your use case is valid.

**Comment by rebello95** [comment]
Circling back to this - still something we want to implement, just haven't gotten to it yet. Keeping this issue open so we don't lose it 😃

**Comment by rebello95** [comment]
I started a draft implementation of this here: https://github.com/connectrpc/connect-swift/pull/186

There's an example of what an implementation could look like here: https://github.com/connectrpc/connect-swift/blob/00d86d094b1d392e8fa9ba8ae46f064e816599af/Libraries/Connect/Interfaces/Interceptors/Interceptor.swift

And the `ConnectInterceptor` has been updated as well in that PR.

I'll revisit this next week to productionize it further.

**Comment by rebello95** [comment]
Some things I want to look into next week:
- Allowing interceptors to fail/reject outbound requests ([like Alamofire does](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#adapting-and-retrying-requests-with-requestinterceptor))
- Whether we should expose async/await interfaces on interceptors (less flexible than closures and more challenging for users who haven't migrated codebases to async/await, but it is more straightforward and modern)
- What additional guardrails can/should be added for streaming (i.e., whether it's worth enforcing that interceptors do not change the order of callbacks for headers and data chunks) without significant complexity

**Comment by rebello95** [comment]
I chatted a bit with @eseay offline before wrapping up the implementation. Decisions and additional notes are documented in the PR: https://github.com/connectrpc/connect-swift/pull/186
