### ISSUE TITLE
Please allow async interceptors

### ISSUE THREAD

**Issue by mycroftcanner** [connectrpc/connect-swift#183]
Could you please allow asynchronous interceptors?

Right now the only I managed to implement authentication was to generate my auth headers asynchronously (as they may be refreshed by gtmappauth):

```
@Sendable func authHeaders() async throws -> Connect.Headers {
      let idToken = try await session.token()
      return ["authorization": ["Bearer \(token)"]]
}
    
 let response = await client.info(request: req, headers: try authHeaders())

**Comment by rebello95** [comment]
Hey @mycroftcanner - thanks for filing this. We're currently tracking this work in https://github.com/connectrpc/connect-swift/issues/104, so I'm going to close this issue as a duplicate.

I'm at a conference this week but will investigate this further when I'm back
