### ISSUE TITLE
Create 0.11.0 release

### ISSUE THREAD

**Issue by scottybobandy** [connectrpc/connect-swift#235]
Hey folks,

Could someone from the team create a new 0.11.0 release, since watch support has been added? 🙏

I haven't got permissions to draft releases for this repo.

Thanks, and happy new year!

**Comment by nicksnyder** [comment]
@rebello95 do you want to tag a release or are you trying to land your other PRs first?

**Comment by rebello95** [comment]
My inclination would be to merge #231 before tagging 0.11.0 since it's closely related to watchOS support. If #234 takes longer to merge, we can tag a separate release after.

Can you pin to the commit you need for now @scottybobandy? Hopefully we can get the above merged quickly.

cc @eseay

**Comment by scottybobandy** [comment]
Yup, not a problem 👍

**Comment by rebello95** [comment]
Tagged: https://github.com/connectrpc/connect-swift/releases/tag/0.11.0
