### ISSUE TITLE
Is it possible to see the underlying request?

### ISSUE THREAD

**Issue by oliverfoggin** [connectrpc/connect-swift#251]
I'm getting some errors setting up this SDK for the first time with a new back end too.

But, I'm not sure where exactly the errors are coming from or why.

Is it possible to see the full underlying request (i.e. path, method, body, host, headers, etc...) so that I can try to debug what I'm doing wrong?

Thanks

**Comment by oliverfoggin** [comment]
I changed from the NIOHttpClient to a URLSessionHTTPClient and it's showing up in Proxyman now 😄

**Comment by rebello95** [comment]
Glad you got this working. I'd generally suggest using `URLSessionHTTPClient` over NIO unless you require the gRPC protocol (lighter binary size and simpler to use).
