### ISSUE TITLE
Inconsistent Timeout Behavior in gRPC with NIOHTTPClient

### ISSUE THREAD

**Issue by davidweissler** [connectrpc/connect-swift#259]
Hi,

We are encountering an issue with the timeout setting in `NIOHTTPClient` when used with `gRPC`. We have configured a timeout of 30 seconds for requests, expecting that any request exceeding this duration should automatically timeout. However, this behavior is inconsistent and hard to reproduce.

Details:

Environment: The issue occurs on iOS 16 and iOS 17, across both iPhone and iPad devices.
Version: Connect 0.12.0.
Issue: Requests occasionally do not timeout after 30 seconds as expected.
Current Workaround: Implemented a manual timeout mechanism that cancels the request at 35 seconds, with these incidents specifically logged.
Configuration: Using `.grpc` for `networkProtocol` and `JSONCodec()` for `codec`.

Question: Are there any known issues with request timeouts in gRPC using NIOHTTPClient that could be causing this behavior? Could you provide guidance on ensuring the timeout setting is consistently respected? Is there a specific configuration tweak required?

Thank you for any help and let me know if there's other info I can provide.

**Comment by rebello95** [comment]
👋🏽 Hi @davidweissler - thank you for the detailed information. How are you setting the timeout today and how did you implement the manual 35 second timeout?

Can you try upgrading to 0.13.0? That version added support for a [`timeout` argument on `ProtocolClientConfig`](https://github.com/connectrpc/connect-swift/pull/247/files#diff-d6cba1360201ea58126e257419fe07db96b12a03b92c1e22bd5a88c804ab2f35R34-R35) which sets the header expected by gRPC services, so I'm curious if that fixes it for you.
