### ISSUE TITLE
Connect-Swift 0.14.0 Podspec

### ISSUE THREAD

**Issue by cnoon** [connectrpc/connect-swift#281]
Hello!

I noticed a mismatch between the Connect-Swift 0.14.0 podspec in trunk vs. the version here in the repo. It looks like the one in `trunk` is locked down to `~> SwiftProtobuf 1.26.0` instead of `~> SwiftProtobuf 1.27.0` like [here](https://github.com/connectrpc/connect-swift/blob/main/Connect-Swift.podspec#L16).

```zsh
❯ cat ./Specs/f/b/3/Connect-Swift/0.14.0/Connect-Swift.podspec.json
{
  "name": "Connect-Swift",
  "module_name": "Connect",
  "version": "0.14.0",
  "license": {
    "type": "Apache 2.0",
    "file": "LICENSE"
  },
  "summary": "Idiomatic gRPC & Connect RPCs for Swift.",
  "homepage": "https://github.com/connectrpc/connect-swift",
  "authors": "The Connect Authors",
  "source": {
    "git": "https://github.com/connectrpc/connect-swift.git",
    "tag": "0.14.0"
  },
  "platforms": {
    "ios": "12.0",
    "osx": "10.15",
    "tvos": "13.0",
    "watchos": "6.0"
  },
  "dependencies": {
    "SwiftProtobuf": [
      "~> 1.26.0"
    ]
  },
  "source_files": "Libraries/Connect/**/*.swift",
  "swift_versions": [
    "5.0"
  ],
  "swift_version": "5.0"
}
```

I noticed this after getting warnings from some newly generated Swift code this morning which I'm assuming is using the new SwiftProtobuf plugin through the `buf` command line tools.

Any help would be greatly appreciated! 🍻

**Comment by cnoon** [comment]
I was able to confirm that pulling in the updated version of `SwiftProtobuf` does resolve the compiler warnings I was seeing.

**Comment by rebello95** [comment]
👋🏽 hey @cnoon - were you using 0.14.0 of Connect-Swift? That podspec has 1.26.0 of SwiftProtobuf pinned: https://github.com/connectrpc/connect-swift/blob/0.14.0/Connect-Swift.podspec#L16

The 1.27.0 version is only on `master` and hasn't yet been tagged in a release of Connect-Swift, so I think the condition you're seeing should only happen if you aren't using a release version of Connect-Swift.

**Comment by rebello95** [comment]
You can now update to the latest RC which includes an updated version of SwiftProtobuf: https://github.com/connectrpc/connect-swift/releases/tag/1.0.0-rc1
