### ISSUE TITLE
Availability of v1.0.0 on the Buf Schema Registry

### ISSUE THREAD

**Issue by bourquep** [connectrpc/connect-swift#320]
Congratulations on the v1 release! 👏🏻

Will we soon see it on the BSR for generated SDKs? For [example](https://buf.build/googleapis/googleapis/sdks):

<img width="1391" alt="image" src="https://github.com/user-attachments/assets/9935e3ef-8b58-41d0-9d17-e781e1fb4690">

**Comment by rebello95** [comment]
👋🏽 looks like this will be available with https://github.com/bufbuild/plugins/pull/1573
